config/routes.rb
Task2::Application.routes.draw do
  get "playlists/index"
  get "playlists/show"
  get "playlists/new"
  get "songs/new"
  root :to => "playlists#index"
  resources :playlists do
    resources :songs
  end
  resources :songs
  resources :playlists
  

end

app/models/playlist.rb
class Playlist < ActiveRecord::Base
  has_many :songs, :dependent => :destroy
end

app/models/song.rb
class Song < ActiveRecord::Base
    belongs_to :playlist
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  def index
      @playlists = Playlist.all
  end

  def show
      @playlists = Playlist.all
      @playlist  = Playlist.find(params[:id])
  end
  
  def new
      @playlist = Playlist.new
  end

  
  def create
      Playlist.create(params[:playlist])
      redirect_to root_path
  end


end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  def new
    @song = Playlist.find(params[:playlist_id]).songs.new
  end


  def create
    playlist = Playlist.find(params[:playlist_id]) 
    playlist.songs.create(params[:song])
    redirect_to playlist
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/playlists/index.html.haml
%h1 Playlists
- @playlists.each do |playlist|
  %p
    %b Dzień:
    =playlist.day
  %p
    %b Autor:
    =playlist.creator
  %p
    %b Nastrój:
    =playlist.mood
  -options = options_for_select( playlist.songs.map {|song| [song.artist + ' - ' + song.title, song.id]} )
  =select_tag(:song_id, options)
  %p
    =link_to "wiecej", playlist
  %hr
%hr
%hr
%p= link_to "Dodaj playlistę", new_playlist_path

app/views/playlists/new.html.haml
- form_for @playlist do |f|
  %p
    Autor:
    = f.text_field :creator
  %p
    Dzień:
    =f.select(:day, options_for_select(1..100) )
  %p
    Nastrój
    = f.text_field :mood
  %p=f.submit "dodaj"
  
%p= link_to "Powrót", playlists_path

app/views/playlists/show.html.haml
%h1 Playlist
%h2
  %p
    Autor: 
    =@playlist.creator
  %p
    Dzień:
    =@playlist.day
  %p
    Nastrój:
    =@playlist.mood
%hr
%h3 Utwory:    
- @playlist.songs.each_with_index do |song, index|
  %p
    %b
      =index+1
      \.
      =song.artist
      \ - 
      =song.title
%br/      
%p= link_to "Dodaj utwór", new_playlist_song_path(@playlist)
%p= link_to "Powrót", playlists_path

app/views/songs/new.html.haml
- form_for [@song.playlist, @song] do |f|
  %p
    Artysta:
    = f.text_field :artist
  %p
    Tytuł:
    = f.text_field :title
  %p=f.submit "dodaj"
  
%p= link_to "Powrót", playlist_path(@song.playlist)